groups:
  - name: octoflow_alerts
    rules:
      - alert: HighCPUUsage
        expr: system_metrics{metric="cpu_usage"} > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage detected
          description: CPU usage is above 90% for 5 minutes

      - alert: HighMemoryUsage
        expr: system_metrics{metric="memory_usage"} > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage detected
          description: Memory usage is above 90% for 5 minutes

      - alert: RedisDown
        expr: redis_health == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Redis connection lost
          description: Redis connection has been down for more than 1 minute

      - alert: RedisCircuitBreakerOpen
        expr: redis_circuit_breaker_status == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Redis circuit breaker is open
          description: Redis circuit breaker has been open for more than 1 minute

      - alert: SlowHTTPRequests
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Slow HTTP requests detected
          description: Average request duration is above 1 second for 5 minutes

      - alert: HighErrorRate
        expr: rate(http_request_duration_seconds_count{code=~"5.."}[5m]) / rate(http_request_duration_seconds_count[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High error rate detected
          description: Error rate is above 5% for 5 minutes

      - alert: SlowComponentRenders
        expr: rate(component_render_duration_seconds_sum[5m]) / rate(component_render_duration_seconds_count[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Slow component renders detected
          description: Average component render time is above 100ms for 5 minutes 