global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'
        labels:
          env: 'production'

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    labels:
      env: 'production'

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    labels:
      env: 'production'

  - job_name: 'octoflow'
    metrics_path: '/api/performance/metrics/prometheus'
    static_configs:
      - targets: ['host.docker.internal:3001']
    labels:
      env: 'production'
    scrape_interval: 10s
    scrape_timeout: 5s 