name: "OctoFlow: Startup GitHub Health Analysis"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  schedule:
    # Run daily at midnight UTC
    - cron: "0 0 * * *"
  # Allow manual triggering
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for accurate PR analysis
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Security audit
        run: npm audit --production
      
      - name: Run Startup GitHub Health Analysis
        id: pr_analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          IS_PR_EVENT: ${{ github.event_name == 'pull_request' }}
        run: |
          ./run-analysis.sh
          # If this is a PR event, create a summary file for commenting
          if [ "$IS_PR_EVENT" = "true" ]; then
            node src/scripts/generatePRComment.js
            echo "summary_path=./data/pr-comment.md" >> $GITHUB_OUTPUT
          fi
      
      - name: Comment on PR with Startup GitHub Health Insights
        if: github.event_name == 'pull_request' && steps.pr_analysis.outputs.summary_path
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const prNumber = context.payload.pull_request.number;
            const summaryPath = '${{ steps.pr_analysis.outputs.summary_path }}';
            
            if (fs.existsSync(summaryPath)) {
              const summary = fs.readFileSync(summaryPath, 'utf8');
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: summary
              });
              console.log('Posted OctoFlow Startup GitHub Health analysis to PR #' + prNumber);
            } else {
              console.log('No summary file found at ' + summaryPath);
            }
      
      - name: Generate GitHub Health Report
        if: github.event_name != 'pull_request'
        run: |
          node src/scripts/generateHealthReport.js
      
      - name: Commit and push results
        if: github.event_name != 'pull_request'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/
          git commit -m "Update GitHub Health Report [skip ci]" || echo "No changes to commit"
          git push 